### ISSUE TITLE
네더라이트 도구 이름에서 네더라이트가 네테라이트로 출력됩니다.

### ISSUE THREAD

**Issue by Haru1234500** [TrueToneTeam/KoreanPack#1]
네더라이트 도구의 이름에서 네더라이트가 전부 네테라이트로 출력됩니다.(네테라이트 헬멧, 네테라이트 가슴판, 네테라이트 레깅스, 네테라이트 부츠, 네테라이트 검, 네테라이트 도끼, 네테라이트 곡괭이, 네테라이트 삽, 네테라이트 괭이)

**Comment by TrueToneTeam** [comment]
해당 리소스 팩에서는 정상적으로 네더라이트라고 번역되어 있습니다.
