### ISSUE TITLE
일부 번역 오류 + 질문사항

### ISSUE THREAD

**Issue by minejango2** [TrueToneTeam/KoreanPack#2]
안녕하세요, 번역에 관심이 많아 크라우딘에도 참여하는 사람입니다. 되게 흥미로운 리소스팩이더군요. 다만, 번역 오류를 몇개 발견하였습니다.

번역 오류(Java Edition과 번역을 맞추는 리소스팩일 경우)
1. 짙은 참나무 버튼이 어두운 참나무 버튼이라고 되어있습니다.
2. 짙은 참나무 압력판이 어두운 참나무 압력판이라고 되어있습니다.
3. 짙은 프리즈머린 계열의 블록 전부가 어두운 프리즈머린이라고 번역되어있습니다.
4. Java Edition 1.19 업데이트로 '정글 나무'를 '정글나무'로 붙여써야 합니다.
5. 'World'는 '월드'가 아닌 '세계'로 번역해야 합니다.

근데, 이 리소스팩은 Java Editon과의 번역을 똑같이 만들려고 만든 리소스팩인가요? 아니면 Java Edition의 번역 중 일부를 바꾸어 번역하나요?

**Comment by TrueToneTeam** [comment]
알려주신 부분 수정하겠습니다.

 Bedrock Edition에서 이상하게 번역된 부분을 Java Edition과 맞추는데, 사람들에게 더 익숙하거나 자주 사용하는 번역이 있다면 기존 Java Edition 번역이 아닌 자주 사용하는 번역으로 수정했습니다.
